### PR TITLE
Include minified build in npm package

### LINKED ISSUE #31: Request: Include browser builds in npm package
This would enable people to use `npmcdn.com/yaku` in their webpages which don't have a build-step.

### PR DESCRIPTION
**Pull request by JakeChampion**
This should resolve #31

### CODE REVIEW

**Comment by ysmood** [comment]
Thanks!

**Comment by JakeChampion** [comment]
Thanks for merging. Do you know when you are next pushing a release to NPM?

**Comment by ysmood** [comment]
Sorry, I forget that. Your change has been published. `yaku@0.16.3`

**Comment by JakeChampion** [comment]
I just noticed this isn't the same as the `yaku.browser.min.js` file that is added to the releases page on Github. How could I get that file added to the npm package?

**Pull request merged**
